import { URL_API, PORT_ESTADO_CIVIL, CONTEXT_AUDITORIA_MEDICA, CONTEXT_LOGIN_TOOLS, CONTEXT_TURNOS, CONTEXTO_LISTADOS, CONTEXT_IMPORTAR, CONTEXT_PRESTACIONES, CONTEXT_CIRUGIAS } from './baseContextURL'

//WS AUDITORIA MEDICA:
export const URL_GET_CANTIDAD_NOTIFICACIONES_AM = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/cantidades-notificaciones`
export const URL_GET_DATA_TABLERO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/cantidades-indicadores`
export const URL_GET_INDICADORES_SINIESTROS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/cantidades-indicadores-siniestros`
export const URL_GET_AUTORIZACIONES_PENDIENTES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/autorizaciones/autorizaciones-pendientes`
export const URL_GET_NUEVOS_INGRESOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/nuevos-ingresos`
export const URL_GET_SINIESTROS_ACTIVOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/siniestros-auditoria-medica/findall`
export const URL_GET_SINIESTROS_ILT_VENCIDOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/siniestros-auditoria-medica/ilt-vencidos`
export const URL_GET_MATERIALES_QX_AUTORIZACION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/materiales-quirurgicos`
export const URL_DATOS_AUTORIZACIONES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/autorizaciones/id`
export const URL_APROBAR_AUTORIZACION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/autorizaciones/autorizar`
export const URL_SET_MATERIALES_QUIRURGICOS_AUTORIZACION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/materiales-quirurgicos/save`
export const URL_DATA_AUTORIZACIONES_PENDIENTES_APROBACION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/autorizaciones/pendientes-por-denuncia`
export const URL_GET_DATA_PEDIDOS_MATERIALES_QX = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/pedidos-materiales-quirurgicos-por-denuncia`
export const URL_SAVE_NUEVO_PROXIMO_CONTACTO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/agendarProximoContactoAudMed`
export const URL_VERIFICAR_ALARMA_ESTUDIOS_PENDIENTES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/verificar-alarma-estudios-pendientes`
export const URL_GUARDAR_DATOS_DENUNCIA_AUDITORIA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/save`
export const URL_GET_MATERIALES_QX= `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/materiales-quirurgicos`
export const URL_VALIDAR_MATERIALES_QX = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_AUDITORIA_MEDICA}/auditoria-medica/materiales-quirurgicos/validarPedido`

//WS TURNOS:
export const URL_GET_HISTORIAL_POR_DENUNCIA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_TURNOS}/turnos/por-denuncia`
export const URL_GET_HISTORIAL_POR_TURNO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_TURNOS}/turnos/historial-por-turno`

//WS LOGINTOOLS:
export const URL_SAVE_PARAMETROS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_LOGIN_TOOLS}/parametros/save`
export const URL_GET_PARAMETROS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_LOGIN_TOOLS}/parametros/by-usuario`

//WS LISTADOS:
export const URL_FETCH_LISTADO_TIPO_TURNO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/tipo-turno`
export const URL_FETCH_LISTADO_EMPLEADORES_POR_AUDITOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/cliente/clientes-por-auditor-medico`
export const URL_FETCH_LISTADO_TRAMITADORES_POR_AUDITOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/tramitador/tramitador-por-auditor-medico`
export const URL_FETCH_LISTADO_MATERIALES_QUIRURGICOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/materiales-quirurgicos`
export const FETCH_URL_GET_LISTADO_TIPO_SOLICITUDES_GENERICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/tipos-solicitudes-genericas`
export const FETCH_URL_GET_LISTADO_ESTADO_SOLICITUDES_GENERICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/estados-solicitudes-genericas`
export const FETCH_URL_GET_LISTADO_AREA_GESTION_SOLICITUDES_GENERICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/areas-gestion-solicitudes-genericas`
export const URL_FETCH_VALORES_PREDETERMINADOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/solicitudes-genericas/valores-predeterminados`
export const URL_FETCH_LISTADO_REGION_PATOLOGICA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/region-patologia`
export const URL_FETCH_LISTADO_SEVERIDAD = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/severidad`
export const URL_FETCH_LISTADO_CAUSA_ILT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/excedente-ilt/motivos`
export const URL_FETCH_LISTADO_SUB_CAUSA_ILT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/excedente-ilt/submotivos`
export const URL_FETCH_LISTADO_ESTADOS_CIRUGIAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/estados-cirugias/findAll`
export const URL_FETCH_LISTADO_MOTIVOS_ANULACION_CIRUGIAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/motivosAnulacionCirugias/findAll`

//WS IMPORTAR EXPORTAR:
export const FETCH_URL_DESCARGAR_PDF_AUTORIZACION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_IMPORTAR}/pdf/descargar/autorizacion`
export const FETCH_URL_DESCARGAR_PDF_ORDEN_MEDICA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_IMPORTAR}/pdf/descargar/pedido-materiales-quirurgicos`

//WS PRESTACIONES:
export const FETCH_URL_FIND_ALL_PRESTACIONES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PRESTACIONES}/prestaciones/findAll`

//WS CIRUGIAS
export const URL_GET_DATOS_CIRUGIAS_POR_DENUNCIA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CIRUGIAS}cirugia/findByDenuncia`
export const URL_GET_OBSERVACIONES_POR_CIRUGIA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CIRUGIAS}cirugia/observaciones`
export const URL_SAVE_OBSERVACION_CIRUGIA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CIRUGIAS}cirugia/observacion/save`
export const URL_ANULAR_CIRUGIA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CIRUGIAS}cirugia/anular`
