import { URL_API, PORT_ESTADO_CIVIL, CONTEXT_PROVEEDOR, CONTEXT_PRESTACIONES, CONTEXT_MODULO_CONVENIO, CONTEXT_CONVENIO, CONTEXTO_LISTADOS, CONTEXT_IMPORTAR } from './baseContextURL'

//WS PROVEEDOR
export const FECTH_URL_SEDE = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/sedes/tiposede`
export const FETCH_URL_BUSQUEDA_CENTROS_MEDICOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/centrosmedicos/super`
export const FETCH_URL_CENTROS_MEDICOS_A_DETERMINAR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/centrosmedicos/adeterminar`
export const FETCH_URL_CENTROS_MEDICOS_SUGERIDOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/centrosmedicos/sugeridos`
export const FETCH_URL_ENVIAR_MAIL_PRIMERA_ASISTENCIA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/centrosmedicos/super/mail/primerasistencia`
export const FECTH_URL_TIPO_SEDE = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/tipossedes/empleador`
export const FECTH_URL_BUSQUEDA_PRESTADOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/proveedor`
export const FECTH_URL_CAMBIO_ESTADO_PROVEEDOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/proveedor/cambiar-estado`
export const FECTH_URL_VALIDACION_CUIT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/proveedor/validar-cuit`
export const FECTH_URL_SAVE_PROVEEDOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/proveedor/save`
export const FETCH_URL_FIND_TIPOS_PROVEEDOR_DATOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/proveedor/tipo-proveedor-datos`
export const FETCH_URL_FIND_CONTACTOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/contacto/findByProveedor`
export const FETCH_URL_SAVE_CONTACTOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/contacto/save`
export const FETCH_URL_DELETE_CONTACTOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/contacto/delete`
export const FETCH_URL_UPDATE_CONTACTOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/contacto/update`
export const FETCH_URL_SAVE_ALL_PROVEEDOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}proveedor/editar-proveedor`
export const FETCH_URL_ESTADO_SUBPRESTADOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/proveedor/cambiar-estado`
export const FETCH_URL_LISTAR_SUBPRESTADOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/sub-prestador/find-by-proveedor`
export const FETCH_URL_SAVE_SUBPRESTADOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}sub-prestador/save`
export const FETCH_URL_UPDATE_SUBPRESTADOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/sub-prestador/update`
export const FETCH_URL_PROVEEDOR_CONVENIO_ACTIVO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PROVEEDOR}/proveedor/convenio-activo`

//WS PRESTACIONES
export const FETCH_URL_LISTADO_PRESTACIONES_NOMENCLADAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PRESTACIONES}/nomencladas`
export const FETCH_URL_LISTADO_PRESTACIONES_NO_NOMENCLADAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PRESTACIONES}/nonomencladas`
export const SAVE_URL_PRESTACION_NO_NOMENCLADA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PRESTACIONES}/nonomencladas/save`
export const EDIT_URL_PRESTACION_NO_NOMENCLADA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PRESTACIONES}/nonomencladas/update`
export const FETCH_URL_PRESTACIONES_PROVEEDOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_PRESTACIONES}/prestaciones/proveedor`

//WS MODULOS
export const FETCH_URL_MODULOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/modulo/find`
export const FETCH_URL_INCLUSIONES_MODULO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/modulo/find-prestaciones/by-modulo`
export const FETCH_URL_INCLUSIONES_REPETIDAS_PNN = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/prestacion-no-nomenclada/identificar-repetidas`
export const FETCH_URL_INCLUSIONES_REPETIDAS_PN = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/nomencladas/identificar-repetidas`
export const SAVE_URL_INCLUSIONES_MODULO_PNN = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/prestacion-no-nomenclada/incluir-a-modulo`
export const SAVE_URL_INCLUSIONES_MODULO_PN = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/nomencladas/incluir-a-modulo`
export const SAVE_URL_MODULO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/modulo/save`
export const EDIT_URL_MODULO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/modulo/editar`
export const FETCH_URL_GET_CONVENIOS_INCLUIDOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/modulo/convenios-incluido`
export const FETCH_URL_LISTADO_MODULOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/modulo`
export const FETCH_URL_IMPACTAR_CONVENIOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_MODULO_CONVENIO}/convenio/editar-impactar-modulo`

//WS CONVENIO
export const URL_GET_CONVENIO_ACTUAL = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual`
export const URL_GET_PN = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/prestaciones-nomencladas`
export const URL_GET_PNN = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/prestaciones-no-nomencladas`
export const URL_GET_PNBU = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/prestaciones-nbu`
export const URL_GET_MODULOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/modulos`
export const URL_GET_MODULOS_AND_INCLUSIONES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/modulos/export`
export const URL_GET_VERSIONAR_CONVENIO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio/versionar`
export const URL_IS_IN_CONVENIO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/inclusiones`
export const FETCH_URL_PRESTACIONES_PREQUIRURGICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/prestaciones-preqx`
export const URL_GET_CONVENIO_HISTORICO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-historico`
export const URL_GET_CONVENIO_TRASLADO_HISTORICO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-historico/convenios-traslados`
export const URL_GET_CONVENIO_TRASLADO_HISTORICO_DETALLE = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-historico/convenios-traslados/byIdConvenio`
export const URL_GET_PN_HISTORICO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-historico/prestaciones-nomencladas`
export const URL_GET_PNN_HISTORICO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-historico/prestaciones-no-nomencladas`
export const URL_GET_PNBU_HISTORICO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-historico/prestaciones-nbu`
export const URL_GET_MODULOS_HISTORICOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-historico/modulos`
export const URL_RESTAURAR_REVISION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-historico/restaurar-convenio`
export const URL_GET_CONVENIO_FUTURO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-futuro/convenios`
export const URL_GET_PN_FUTURO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-futuro/prestaciones-nomencladas`
export const URL_GET_PNN_FUTURO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-futuro/prestaciones-no-nomencladas`
export const URL_GET_PNBU_FUTURO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-futuro/prestaciones-nbu`
export const URL_GET_MODULOS_FUTURO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-futuro/modulos`
export const URL_DELETE_CONVENIO_FUTURO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-futuro/eliminar-convenio`
export const URL_SAVE_CONVENIO_FUTURO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-futuro/editar-convenio`
export const URL_IMPORTAR_PN = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/importar/prestaciones-nomencladas`
export const URL_IMPORTAR_PNN = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/importar/prestaciones-no-nomencladas`
export const URL_IMPORTAR_MODULOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/importar/modulos`
export const URL_GET_CONVENIO_TRASLADO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/traslado`
export const URL_POST_CONVENIO_TRASLADO_AJUSTAR_PORCENTAJE = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-actual/traslado/ajuste-porcentaje`
export const URL_ALTA_CONVENIO_TRASLADO= `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-traslado/guardar`
export const URL_POST_EDITAR_CONVENIO_TRASLADO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONVENIO}/convenio-traslado/editar`

//WS LISTADOS:
export const FETCH_URL_LISTADO_TIPO_HABITACION_HOTELES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/hotel/tipo-habitacion`
export const FETCH_URL_ESPECIALIDADES_MEDICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/especialidades-medicas`
export const FETCH_URL_VISIBILIDAD_CONTACTO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/contacto/tipo-visibilidad`
export const FETCH_URL_PRESTACIONES_CATEGORIAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/prestaciones/categorias`
export const FETCH_URL_PRESTACIONES_CATEGORIAS_CONTRATACIONES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/prestaciones/categorias-contrataciones`
export const FETCH_URL_PRESTACIONES_SUBCATEGORIAS_CONTRATACIONES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/prestaciones/sub-categorias-contrataciones`
export const FETCH_URL_LISTADO_TIPO_SUBPRESTADORES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/sub-prestador/tipo`
export const FETCH_URL_LISTADO_TIPO_PRESTADOR_SELECT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/tipo-proveedor`
export const FETCH_URL_CENTROS_MEDICOS_PROPIOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/centros-medicos-propios`
export const FETCH_URL_TIPO_PRESTADOR_MEDICO_SELECT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/tipos-centros-medicos`
export const FETCH_URL_LISTADO_TIPOS_PERSONAS_SELECT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/tipo-persona`
export const FETCH_URL_LISTADO_TIPOS_CONTACTOS_SELECT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/tipos-contactos`
export const FETCH_URL_PRESTADOR_MEDICO_TIPOS_SELECT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/proveedor-centro-medico/tipo`
export const FETCH_URL_LISTADO_ESTADO_SELECT = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/estado`
export const FETCH_URL_LISTADO_PROVINCIA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/ubicacion/provincia`
export const FETCH_URL_GET_LISTADOS_TIPO_PRESTACION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/tipo-prestaciones`
export const FETCH_URL_LISTADO_TIPO_VALOR_VIAJE_NEGATIVO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/convenio-traslado/listado-tipo-valor`
export const FETCH_URL_LISTADO_DESTINO_FRECUENTE=`${URL_API}${PORT_ESTADO_CIVIL}${CONTEXTO_LISTADOS}/convenio-traslado/listado-destino-frecuente`

//WS IMPORTAR EXPORTAR
export const FECTH_URL_EXPORTAR_CONSULTA_GENERICA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_IMPORTAR}/reporte/excel-generico`
export const FECTH_URL_IMPORTAR_SUBPRESTADORES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_IMPORTAR}/import/excel/subprestador`
export const FECTH_URL_IMPORTAR_LOCALIDADES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_IMPORTAR}/import/excel/localidad`
export const FETCH_URL_DESCARGAR_PDF_HISTORICO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_IMPORTAR}/pdf/descargar/convenio-historico`
export const FETCH_URL_EXPORTAR_PDF_CONVENIO_TRASLADO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_IMPORTAR}/pdf/convenio-traslado-actual`
