import { CONTEXT_CONTACTO, CONTEXT_NOTIFICACIONES, PORT_ESTADO_CIVIL, URL_API } from "./baseContextURL"

//WS CONTACTOS:
export const FECTH_URL_CONTACTOS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_CONTACTO}/contactos`

//WS NOTIFICACIONES:
export const FECTH_URL_NOTIFICACIONES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_NOTIFICACIONES}/notificacion/operador/all`
export const FECTH_URL_MARCAR_VISTA_NOTIFICACION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_NOTIFICACIONES}/notificacion/id/vista`
export const FECTH_URL_ELIMINAR_NOTIFICACION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_NOTIFICACIONES}/notificacion/id/delete`
export const FECTH_URL_CAMPANA_NOTIFICACIONES = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_NOTIFICACIONES}/notificacion/operador/cantidad`
