import { URL_API, PORT_ESTADO_CIVIL, CONTEXT_SOLICITUDES_GENERICAS, CONTEXT_NOTIFICACIONES, CONTEXT_IMPORTAR } from './baseContextURL'

//WS SOLICITUDES GENERICAS
export const FECTH_URL_SEARCH_SOLICITUDES_GENERICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/findall`
export const FETCH_ASIGNAR_SOLICITUDES_GENERICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/id/asignar`
export const FETCH_DESAASIGNAR_SOLICITUDES_GENERICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/id/desasignar`
export const FETCH_CERRAR_SOLICITUD_GENERICA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/cerrar`
export const FETCH_MARCAR_VISTA_SOLICITUD_GENERICA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/id/marcarvista`
export const FETCH_URL_SET_DATOS_SOLICITUD = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/find-by-id`
export const FETCH_URL_SET_DATOS_SEGUIMIENTO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/seguimientos`
export const FETCH_URL_SOLICITUDES_MAS_INFO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitud-mas-info/findBySolicitudGenerica`
export const FETCH_URL_SOLICITUD_MAS_INFO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitud-mas-info/find-by-id`
export const FETCH_URL_SET_NUEVA_SOLICITUD = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/alta-solicitud-generica`
export const FETCH_URL_REABRIR_SOLICITUD = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/reabrir`
export const FETCH_URL_CALIFICAR_GESTION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/calificar`
export const FETCH_URL_DERIVAR_SOLICITUD = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/derivar`
export const FETCH_URL_RECHAZAR_SOLICITUD = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/rechazar`
export const FETCH_URL_REASIGNAR_SOLICITUD = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/reasignar-masivamente`
export const FETCH_URL_NUEVO_SEGUIMIENTO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/nuevo-seguimiento`
export const FETCH_URL_GET_CANTIDAD_SOLICITUDES_GESTOR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/cantidad-solicitudes`
export const FETCH_URL_NUEVA_MAS_INFO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitud-mas-info/crear`
export const FETCH_URL_RESPONDER_MAS_INFO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitud-mas-info/responder`
export const FETCH_URL_ASIGNAR_GESTOR_MAS_INFO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitud-mas-info/asignar-gestor`
export const FETCH_URL_CANTIDADES_SOLICITUD_GENERICAS = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/find-cantidad-solicitudes-genericas`
export const FETCH_URL_GET_SOLICITANTE_GESTOR_POR_AREA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/personas-por-area`
export const FETCH_URL_PERSONAS_BY_AREA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/personas-by-area`
export const FETCH_URL_AREAS_DE_GESTION = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/areas-gestion`
export const FETCH_URL_TIPOS_SOLICITUD = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/tipos-solicitudes`
export const FETCH_URL_EXISTEN_SG_SIN_ASIGNAR = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_SOLICITUDES_GENERICAS}/solicitudesgenericas/existen-solicitudes-genericas-sin-asignar`

//WS NOTIFICACIONES
export const FETCH_URL_NOTIFICACIONES_MAS_INFO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_NOTIFICACIONES}/notificacion/solicitudes-mas-info`
export const FETCH_URL_MARCAR_MAS_INFO_COMO_VISTA = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_NOTIFICACIONES}/notificacion/solicitudes-mas-info/vista`
export const FETCH_URL_CANTIDAD_NOTIFICACIONES_MAS_INFO = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_NOTIFICACIONES}/notificacion/solicitudes-mas-info/cantidad-sin-ver`

//WS IMPORTAR EXPORTAR
export const FETCH_URL_DESCARGAR_PDF_INICIO_SG = `${URL_API}${PORT_ESTADO_CIVIL}${CONTEXT_IMPORTAR}/descarga/solicitudes-genericas`