export const SET_ZONA_AFECCION = "SET_ZONA_AFECCION"
export const SET_ZONA_AFECCION_2 = "SET_ZONA_AFECCION_2"
export const SET_ZONA_AFECCION_3 = "SET_ZONA_AFECCION_3"
export const SET_ESTADO_CIVIL = "SET_ESTADO_CIVIL"

//DOCUMENTO
export const SET_DENUNCIAS = 'SET_DENUNCIAS'
export const SET_DENUNCIAS_TABLERO_COMPLETO = 'SET_DENUNCIAS_TABLERO_COMPLETO'
export const SET_DENUNCIAS_TABLERO_BORRADOR = 'SET_DENUNCIAS_TABLERO_BORRADOR'
export const SET_DENUNCIAS_TABLERO_INCOMPLETO = 'SET_DENUNCIAS_TABLERO_INCOMPLETO'
export const SET_CANTIDAD_DENUNCIAS = 'SET_CANTIDAD_DENUNCIAS'
export const SET_DENUNCIA = 'SET_DENUNCIA'
export const SET_LOADING_DENUNCIA = 'SET_LOADING_DENUNCIA'
export const SET_TIPO_SEDE = 'SET_TIPO_SEDE'
export const SET_SEDE = 'SET_SEDE'
export const LOADING_DENUNCIAS_ANTERIORES_REINGRESO = 'LOADING_DENUNCIAS_ANTERIORES_REINGRESO'
export const LOADING_PRE_DENUNCIAS = 'LOADING_PRE_DENUNCIAS'
export const BUSQUEDA_CENTRO_MEDICO = 'BUSQUEDA_CENTRO_MEDICO'
export const GET_CAMPOS_REQUERIDOS = 'GET_CAMPOS_REQUERIDOS'
export const SET_LOADING_ENVIAR_A_PENDIENTES = 'SET_LOADING_ENVIAR_A_PENDIENTES'
export const SET_LOADING_SINIESTRO_MULTIPLE_SAVE_DENUNCIA = 'SET_LOADING_SINIESTRO_MULTIPLE_SAVE_DENUNCIA'
export const LOADING_BUSQUEDA_PRESTADOR = 'LOADING_BUSQUEDA_PRESTADOR'
export const SET_DATA_PRESTADOR = 'SET_DATA_PRESTADOR'
export const SET_CORTO_PUNZANTE_ANTERIOR_ACTIVO = "SET_CORTO_PUNZANTE_ANTERIOR_ACTIVO"
export const LOADING_GENERAR_PREDENUNCIA = "LOADING_GENERAR_PREDENUNCIA"
export const SET_LOADING_CAMPOS_REQUERIDOS = 'SET_LOADING_CAMPOS_REQUERIDOS'
export const SET_REDUX_DENUNCIA_SNACKBAR = 'SET_REDUX_DENUNCIA_SNACKBAR'
export const SET_EXISTEN_PREDENUNCIAS_SIN_ASIGNAR = 'SET_EXISTEN_PREDENUNCIAS_SIN_ASIGNAR'
export const SET_LOADING_BUSQUEDA_PRESTADOR_BUSCADOR = "SET_LOADING_BUSQUEDA_PRESTADOR_BUSCADOR"
export const SET_DATA_PRESTADORES_BUSCADOR = "SET_DATA_PRESTADORES_BUSCADOR"

//LISTADO
export const SET_NACIONALIDAD = 'SET_NACIONALIDAD'
export const SET_ESTADO_MEDICO = 'SET_ESTADO_MEDICO'
export const SET_ESTADO_SEVERIDAD_DENUNCIA = 'SET_ESTADO_SEVERIDAD_DENUNCIA'
export const SET_TIPO_SINIESTRO = 'SET_TIPO_SINIESTRO'
export const SET_CIRCUNSTANCIA = 'SET_CIRCUNSTANCIA'
export const SET_LUGAR_ACCIDENTE = 'SET_LUGAR_ACCIDENTE'
export const SET_PATOLOGIA_TRAZADORA = 'SET_PATOLOGIA_TRAZADORA'
export const SET_AGENTE_CAUSANTE = 'SET_AGENTE_CAUSANTE'
export const SET_AGENTE_MATERIAL = 'SET_AGENTE_MATERIAL'
export const SET_DIAGNOSTICO_CIE10 = 'SET_DIAGNOSTICO_CIE10'
export const SET_DIAGNOSTICO_CIE10_2 = 'SET_DIAGNOSTICO_CIE10_2'
export const SET_DIAGNOSTICO_CIE10_3 = 'SET_DIAGNOSTICO_CIE10_3'
export const SET_OCUPACION = 'SET_OCUPACION'
export const SET_TAREA = 'SET_TAREA'
export const SET_EXTRACCIONISTA = 'SET_EXTRACCIONISTA'
export const SET_NATURALEZA_SINIESTRO = 'SET_NATURALEZA_SINIESTRO'
export const SET_NATURALEZA_SINIESTRO_2 = 'SET_NATURALEZA_SINIESTRO_2'
export const SET_NATURALEZA_SINIESTRO_3 = 'SET_NATURALEZA_SINIESTRO_3'
export const SET_TRAMITADOR = 'SET_TRAMITADOR'
export const SET_TIPO_DNI = 'SET_TIPO_DNI'
export const SET_DENUNCIANTE_VIP = 'SET_DENUNCIANTE_VIP'
export const SET_LOADING_DENUNCIANTE_VIP = 'SET_LOADING_DENUNCIANTE_VIP'
export const SET_LOADING_ADD_PERSONAL_VIP = ' SET_LOADING_ADD_PERSONAL_VIP'
export const SET_PRESENTA_COVID = 'SET_PRESENTA_COVID'
export const SET_OPERADORES = 'SET_OPERADORES'
export const SET_ESTADO_CONSULTAS_Y_RECLAMOS = 'SET_ESTADO_CONSULTAS_Y_RECLAMOS'
export const SET_SINIESTROS_ANTERIORES = 'SET_SINIESTROS_ANTERIORES'
export const SET_LOADING_CARDS = 'SET_LOADING_CARDS'
export const SET_SEXO = 'SET_SEXO'
export const SET_CENTRO_MEDICO_SUGERIDO = 'SET_CENTRO_MEDICO_SUGERIDO'
export const SET_TIPO_VIAJE = 'SET_TIPO_VIAJE'
export const SET_CODIGO_AMBULANCIA = 'SET_CODIGO_AMBULANCIA'
export const SET_TIPO_TRASLADOS = 'SET_TIPO_TRASLADOS'
export const SET_FORMA_ACCIDENTE = 'SET_FORMA_ACCIDENTE'
export const SET_TIPO_CONTACTO = 'SET_TIPO_CONTACTO'
export const SET_PROCESOS = 'SET_PROCESOS'
export const SET_AMBULANCIAS = 'SET_AMBULANCIAS'
export const LOADING_AMBULANCIAS = 'LOADING_AMBULANCIAS'
export const SET_PROVEEDOR_TRASLADOS = 'SET_PROVEEDOR_TRASLADOS'
export const SET_ESTADO_INTERNACION = 'SET_ESTADO_INTERNACION'
export const SET_LOADING_UPDATE = 'SET_LOADING_UPDATE'
export const SET_LOADING_UPDATE2 = 'SET_LOADING_UPDATE2'
export const SET_ESTADO_TRASLADO = 'SET_ESTADO_TRASLADO'
export const SET_AUDITOR = 'SET_AUDITOR'
export const SET_TRAMITADOR_SUGERIR = 'SET_TRAMITADOR_SUGERIR'
export const SET_LISTADO_MODALIDAD_TRABAJO = 'SET_LISTADO_MODALIDAD_TRABAJO'
export const SET_LISTADO_TIPO_PRESTADOR_SELECT = 'SET_LISTADO_TIPO_PRESTADOR_SELECT'
export const SET_LISTADO_ESTADO_SELECT = 'SET_LISTADO_ESTADO_SELECT'
export const SET_LISTADO_PRESTADOR_MEDICO_TIPOS_SELECT = 'SET_LISTADO_PRESTADOR_MEDICO_TIPOS_SELECT'
export const LISTAR_CLIENTES = "LISTAR_CLIENTES"
export const LISTAR_PRESTADOR = "LISTAR_PRESTADOR"
export const LISTAR_PRIMERA_ASISTENCIA = "LISTAR_PRIMERA_ASISTENCIA"
export const LISTAR_PROVINCIAS = "LISTAR_PROVINCIAS"
export const SET_TIPOS_CONTACTOS = "SET_TIPOS_CONTACTOS"
export const SET_TIPO_PERSONAS = "SET_TIPO_PERSONAS"
export const LISTAR_TIPO_PRESTADOR_MEDICO = "LISTAR_TIPO_PRESTADOR_MEDICO"
export const LISTAR_CENTROS_MEDICOS_PROPIOS = "LISTAR_CENTROS_MEDICOS_PROPIOS"
export const SET_ESPECIALIDADES_MEDICAS = "SET_ESPECIALIDADES_MEDICAS"
export const SET_TIPO_CONTACTOS_SELECT = "SET_TIPO_CONTACTOS_SELECT"
export const SET_VISIBILIDAD_CONTACTO = "SET_VISIBILIDAD_CONTACTO"
export const SET_TIPO_HABITACION = "SET_TIPO_HABITACION"
export const SET_TIPO_SUBPRESTADOR = "SET_TIPO_SUBPRESTADOR"
export const GET_PRESTACIONES_CATEGORIAS = "GET_PRESTACIONES_CATEGORIAS"
export const GET_PRESTACIONES_CATEGORIAS_CONTRATACIONES = "GET_PRESTACIONES_CATEGORIAS_CONTRATACIONES"
export const GET_PRESTACIONES_SUBCATEGORIAS_CONTRATACIONES = "GET_PRESTACIONES_SUBCATEGORIAS_CONTRATACIONES"
export const SET_TIPOS_SOLICITUDES_GENERICAS = "SET_TIPOS_SOLICITUDES_GENERICAS"
export const SET_AREA_GESTION = "SET_AREA_GESTION"
export const SET_ESTADOS_SOLICITUDES_GENERICA = "SET_ESTADOS_SOLICITUDES_GENERICA"
export const SET_DATA_NOTIFICACIONES_MAS_INFO = "SET_DATA_NOTIFICACIONES_MAS_INFO"
export const SET_LOADING_NOTIFICACIONES_MAS_INFO = "SET_LOADING_NOTIFICACIONES_MAS_INFO"
export const SET_ERROR_NOTIFICACIONES_MAS_INFO = "SET_ERROR_NOTIFICACIONES_MAS_INFO"
export const SET_LISTADO_INDICADORES_SINIESTROS = "SET_LISTADO_INDICADORES_SINIESTROS"
export const SET_LOADING_LISTADO_INDICADORES_SINIESTROS = "SET_LOADING_LISTADO_INDICADORES_SINIESTROS"
export const SET_LISTADO_TIPOS_TURNOS = "SET_LISTADO_TIPOS_TURNOS"
export const SET_LISTADO_EMPLEADORES_POR_AUDITOR = "SET_LISTADO_EMPLEADORES_POR_AUDITOR"
export const SET_LISTADO_TRAMITADORES_POR_AUDITOR = "SET_LISTADO_TRAMITADORES_POR_AUDITOR"
export const SET_DATA_LISTADO_MATERIALES_QX = "SET_DATA_LISTADO_MATERIALES_QX"
export const SET_LOADING_LISTADO_MATERIALES_QX = "SET_LOADING_LISTADO_MATERIALES_QX"
export const SET_ERROR_LISTADO_MATERIALES_QX = "SET_ERROR_LISTADO_MATERIALES_QX"
export const SET_LISTADOS_PROVINCIA_VALORES_PREDETERMINADOS = "SET_LISTADOS_PROVINCIA_VALORES_PREDETERMMINADOS"
export const SET_LISTADOS_ESTADOS_VALORES_PREDETERMINADOS = "SET_LISTADO_ESTADOS_VALORES_PREDETERMINADOS"
export const SET_LISTASDOS_MOTIVOS_VALORES_PREDETERMINADOS = "SET_LISTADOS_MOTIVOS_VALORES_PREDETERMINADOS"
export const SET_DATA_LISTADO_REGION_PATOLOGICA = "SET_LISTADO_REGION_PATOLOGICA"
export const SET_DATA_LISTADO_ESTADOS_CIRUGIAS = "SET_DATA_LISTADO_ESTADOS_CIRUGIAS"
export const SET_LOADING_LISTADO_REGION_PATOLOGICA = "SET_LOADING_LISTADO_REGION_PATOLOGICA"
export const SET_LISTADO_SEVERIDAD = "SET_LISTADO_SEVERIDAD"
export const SET_LISTADO_CAUSA_ILT = "SET_LISTADO_CAUSA_ILT"
export const SET_LISTADO_SUB_CAUSA_ILT = "SET_LISTADO_SUB_CAUSA_ILT"
export const SET_LOADING_LISTADO_ESTADOS_CIRUGIAS = "SET_LOADING_LISTADO_ESTADOS_CIRUGIAS"
export const SET_DATA_LISTADO_MOTIVOS_ANULACION_CIRUGIAS = "SET_DATA_LISTADO_MOTIVOS_ANULACION_CIRUGIAS"
export const SET_LOADING_LISTADO_MOTIVOS_ANULACION_CIRUGIAS = "SET_LOADING_LISTADO_MOTIVOS_ANULACION_CIRUGIAS"
export const SET_DATA_TIPO_VALOR_VIAJE_NEGATIVO = "SET_DATA_TIPO_VALOR_VIAJE_NEGATIVO"
export const SET_DATA_LISTADO_DESTINOS_FRECUENTES = "SET_DATA_LISTADO_DESTINOS_FRECUENTES"

//UBICACION
export const SET_PROVINCIAS = 'SET_PROVINCIAS'
export const SET_PROVINCIAS_SELECT = 'SET_PROVINCIAS_SELECT'
export const SET_LOCALIDADES = 'SET_LOCALIDADES'
export const SET_LOCALIDADES_SELECT = 'SET_LOCALIDADES_SELECT'
export const SET_CALLE = 'SET_CALLE'
export const SET_CODIGO_POSTAL = 'SET_CODIGO_POSTAL'
export const SET_CODIGO_POSTAL_CABA = 'SET_CODIGO_POSTAL_CABA'
export const SET_DATA_GRAFICOS = 'SET_DATA_GRAFICOS'
export const SET_PRE_DENUNCIA = 'SET_PRE_DENUNCIA'

//PERSONA
export const SET_BUSQUEDA_EMPLEADOR = "SET_BUSQUEDA_EMPLEADOR"
export const SET_LOADING_NUEVA_DENUNCIA = "SET_LOADING_NUEVA_DENUNCIA"
export const SET_LOADING_SAVE_DENUNCIA = "SET_LOADING_SAVE_DENUNCIA"
export const GET_LISTADO_SINIESTROS_MULTIPLES = "GET_LISTADO_SINIESTROS_MULTIPLES"
export const SET_BUSQUEDA_EMPLEADOR_TODOS = "SET_BUSQUEDA_EMPLEADOR_TODOS"
export const SET_DATOS_PACIENTE = "SET_DATOS_PACIENTE"
export const SET_LOADING_DATOS_PACIENTE = "SET_LOADING_DATOS_PACIENTE"

//SOLICITUDES GENERICAS
export const SET_SOLICITUDES_GENERICAS = "SET_SOLICITUDES_GENERICAS"
export const SET_LOADING_GENERICAS = "SET_LOADING_GENERICAS"
export const SET_SNACKBAR = "SET_SNACKBAR"
export const SET_DATOS_SOLICITUD = "SET_DATOS_SOLICITUD"
export const SET_DATOS_SOLICITUD_DRAWER_NOTIFICACIONES = "SET_DATOS_SOLICITUD_DRAWER_NOTIFICACIONES"
export const SET_DATOS_PRESTADOR = "SET_DATOS_PRESTADOR"
export const SET_DATOS_SEGUIMIENTO = "SET_DATOS_SEGUIMIENTO"
export const SET_DATOS_SOLICITUDES_MAS_INFO = "SET_DATOS_SOLICITUDES_MAS_INFO"
export const SET_DATOS_SOLICITUDES_BY_DENUNCIA = "SET_DATOS_BY_DENUNCIA"
export const SET_DATOS_CABECERA_SOLICITUDES_GENERICAS = "SET_DATOS_CABECERA_SOLICITUDES_GENERICAS"
export const SET_TODAS_SG = "SET_TODAS_SG"
export const SET_LOADING_DATOS_TABLA_SOLICITUDES_BY_DENUNCIA = "SET_LOADING_DATOS_TABLA_BY_DENUNCIA"
export const SET_SOLICITUD_SELECCIONADA = "SET_SOLICITUD_SELECCIONADA"
export const SET_USUARIO_ACTIVO = "SET_USUARIO_ACTIVO"
export const SET_DETALLE_NOTIFICACIONES_MAS_INFO = "SET_DETALLE_NOTIFICACIONES_MAS_INFO"
export const SET_LOADING_DETALLE_NOTIFICACIONES_MAS_INFO = "SET_LOADING_DETALLE_NOTIFICACIONES_MAS_INFO"
export const SET_ERROR_DETALLE_NOTIFICACIONES_MAS_INFO = "SET_ERROR_DETALLE_NOTIFICACIONES_MAS_INFO"
export const SET_ESTADOS_RESPUESTA_MAS_INFO = "SET_ESTADOS_RESPUESTA_MAS_INFO"
export const SET_SOLICITANTE_GESTOR_AREA = "SET_SOLICITANTE_GESTOR_AREA"
export const SET_CANTIDAD_SOLICITUDES = "SET_CANTIDAD_SOLICITUDES"
export const SET_PERSONAS_BY_AREA = "SET_PERSONAS_BY_AREA"
export const SET_LOADING_SEGUIMIENTO = "SET_LOADING_SEGUIMIENTO"
export const SET_ACTUALIZAR_DATA_TABLA_SOLICITUDES = "SET_ACTUALIZAR_DATA_TABLA_SOLICITUDES"
export const SET_LOADING_AUTOSUGGEST = "SET_LOADING_AUTOSUGGEST"
export const SET_MAS_INFO_SELECCIONADA = "SET_MAS_INFO_SELECCIONADA"
export const SET_DATOS_SOLICITUD_MAS_INFO = "SET_DATOS_SOLICITUD_MAS_INFO"
export const SET_CANTIDAD_SOLICITUDES_GENERICAS = "SET_CANTIDAD_SOLICITUDES_GENERICAS"
export const SET_LOADING_CABECERA_SOLICITUDES = "SET_LOADING_CABECERAS_SOLICITUDES"
export const SET_CANTIDAD_NOTIFICACIONES_MAS_INFO = "SET_CANTIDAD_NOTIFICACIONES_MAS_INFO"
export const ACTUALIZAR_NOTIFICACIONES = "ACTUALIZAR_NOTIFICACIONES"
export const ACTUALIZAR_DATA_MAS_INFO = "ACTUALIZAR_DATA_MAS_INFO"
export const SET_NOTIFICACION_TE_RESPONDIERON = "SET_NOTIFICACION_TE_RESPONDIERON"
export const SET_NOTIFICACIONES_GENERALES = "SET_NOTIFICACIONES_GENERALES"
export const SET_AREAS_DE_GESTION = "SET_AREAS_DE_GESTION"
export const SET_TIPOS_SOLICITUD = "SET_TIPOS_SOLICITUD"
export const SET_EXISTEN_SG_SIN_ASIGNAR = "SET_EXISTEN_SG_SIN_ASIGNAR"
export const SET_DATOS_BUSQUEDA_SG_CON_RETORNO = "SET_DATOS_BUSQUEDA_SG_CON_RETORNO"
export const CLEAN_DATOS_BUSQUEDA_SG_CON_RETORNO = "CLEAN_DATOS_BUSQUEDA_SG_CON_RETORNO"

//TRASLADOS
export const SET_LOADING_TRASLADOS = "SET_LOADING_TRASLADOS"
export const SET_TRASLADOS_COMPLETOS = "SET_TRASLADOS_COMPLETOS"
export const SET_TRASLADOS_GENERAL = "SET_TRASLADOS_GENERAL"
export const SET_SERVICIOS_TRASLADOS = "SET_SERVICIOS_TRASLADOS"
export const SET_AGENCIA_TRASLADOS = "SET_AGENCIA_TRASLADOS"
export const SET_DETALLE_TRASLADO = "SET_DETALLE_TRASLADO"
export const SET_EXPORTAR_TRASLADO = "SET_EXPORTAR_TRASLADO"
export const SET_EXPORTAR_TRASLADO_DONE = "SET_EXPORTAR_TRASLADO_DONE"

//CONSULTAS-RECLAMOS
export const SET_EVOLUCIONES = "SET_EVOLUCIONES"
export const SET_LOADING_EVOLUCIONES = "SET_LOADING_EVOLUCIONES"
export const SET_OBSERVACIONES = "SET_OBSERVACIONES"
export const SET_LOADING_OBSERVACIONES = "SET_LOADING_OBSERVACIONES"
export const SET_CONSULTAS_Y_RECLAMOS_COMPLETO = "SET_CONSULTAS_Y_RECLAMOS_COMPLETO"
export const SET_LOADING_RECLAMOS = "SET_LOADING_RECLAMOS"
export const SET_CONSULTAS_Y_RECLAMOS_GENERAL = "SET_CONSULTAS_Y_RECLAMOS_GENERAL"
export const SET_DETALLE_CONSULTA_RECLAMO = "SET_DETALLE_CONSULTA_RECLAMO"
export const LOADING_EDITAR_OBSERVACION = "LOADING_EDITAR_OBSERVACION"
export const LOADING_NUEVA_OBSERVACION = "LOADING_NUEVA_OBSERVACION"

//SINIESTROS CON PENDIENTES
export const SET_SINIESTROS_CON_PENDIENTES = "SET_SINIESTROS_CON_PENDIENTES"
export const SET_LOADING_CON_PENDIENTES = "SET_LOADING_CON_PENDIENTES"

//CONTACTOS
export const SET_CONTACTOS = "SET_CONTACTOS"
export const SET_LOADING_CONTACTOS = "SET_LOADING_CONTACTOS"

//PROVEEDOR
export const SET_LOADING_VALIDACION_CUIT = 'SET_LOADING_VALIDACION_CUIT'
export const FIND_TIPOS_PROVEEDOR_DATOS = 'FIND_TIPOS_PROVEEDOR_DATOS'
export const SET_DATA_CONTACTOS = 'SET_DATA_CONTACTOS'
export const SET_LOADING_BUSQUEDA_CONTACTOS = 'SET_LOADING_BUSQUEDA_CONTACTOS'
export const SET_LISTAR_SUBPRESTADORES = "SET_LISTAR_SUBPRESTADORES"
export const SET_LOADING_LISTAR_SUBPRESTADORES = "SET_LOADING_LISTAR_SUBPRESTADORES"
export const SET_LOADING_SAVE_PRESTADOR = "SET_LOADING_SAVE_PRESTADOR"
export const SET_PROVEEDOR_TRASLADO_ACTIVO="SET_PROVEEDOR_TRASLADO_ACTIVO"


//ERROR AUTOSUGGEST
export const ERROR_AUTOSUGGEST_AGENTE_MATERIAL = "ERROR_AUTOSUGGEST_AGENTE_MATERIAL"
export const ERROR_AUTOSUGGEST_AGENTE_CAUSANTE = "ERROR_AUTOSUGGEST_AGENTE_CAUSANTE"
export const ERROR_AUTOSUGGEST_BUSQUEDA_EMPLEADOR = "ERROR_AUTOSUGGEST_BUSQUEDA_EMPLEADOR"
export const ERROR_AUTOSUGGEST_BUSQUEDA_EMPLEADOR_TODOS = "ERROR_AUTOSUGGEST_BUSQUEDA_EMPLEADOR_TODOS"
export const ERROR_AUTOSUGGEST_DIAGNOSTICO_CIE10 = "ERROR_AUTOSUGGEST_DIAGNOSTICO_CIE10"
export const ERROR_AUTOSUGGEST_DIAGNOSTICO_CIE10_2 = "ERROR_AUTOSUGGEST_DIAGNOSTICO_CIE10_2"
export const ERROR_AUTOSUGGEST_DIAGNOSTICO_CIE10_3 = "ERROR_AUTOSUGGEST_DIAGNOSTICO_CIE10_3"
export const ERROR_AUTOSUGGEST_FORMA_ACCIDENTE = "ERROR_AUTOSUGGEST_FORMA_ACCIDENTE"
export const ERROR_AUTOSUGGEST_NATURALEZA_SINIESTRO = "ERROR_AUTOSUGGEST_NATURALEZA_SINIESTRO"
export const ERROR_AUTOSUGGEST_NATURALEZA_SINIESTRO_2 = "ERROR_AUTOSUGGEST_NATURALEZA_SINIESTRO_2"
export const ERROR_AUTOSUGGEST_NATURALEZA_SINIESTRO_3 = "ERROR_AUTOSUGGEST_NATURALEZA_SINIESTRO_3"
export const ERROR_AUTOSUGGEST_ZONA_AFECCION = "ERROR_AUTOSUGGEST_ZONA_AFECCION"
export const ERROR_AUTOSUGGEST_ZONA_AFECCION_2 = "ERROR_AUTOSUGGEST_ZONA_AFECCION_2"
export const ERROR_AUTOSUGGEST_ZONA_AFECCION_3 = "ERROR_AUTOSUGGEST_ZONA_AFECCION_3"
export const ERROR_AUTOSUGGEST_PROVINCIA = "ERROR_AUTOSUGGEST_PROVINCIA"
export const ERROR_AUTOSUGGEST_LOCALIDADES = "ERROR_AUTOSUGGEST_LOCALIDADES"
export const ERROR_AUTOSUGGEST_CENTROS_MEDICOS = "ERROR_AUTOSUGGEST_CENTROS_MEDICOS"
export const ERROR_AUTOSUGGEST_CALLE = "ERROR_AUTOSUGGEST_CALLE"
export const ERROR_AUTOSUGGEST_CODIGO_POSTAL = "ERROR_AUTOSUGGEST_CODIGO_POSTAL"
export const ERROR_AUTOSUGGEST_OCUPACION = "ERROR_AUTOSUGGEST_OCUPACION"
export const ERROR_AUTOSUGGEST_TAREA = "ERROR_AUTOSUGGEST_TAREA"
export const ERROR_AUTOSUGGEST_SEDE = "ERROR_AUTOSUGGEST_SEDE"
export const ERROR_AUTOSUGGEST_TIPO_SEDE = "ERROR_AUTOSUGGEST_TIPO_SEDE"
export const ERROR_AUTOSUGGEST_PROVEEDOR_TRASLADO = "ERROR_AUTOSUGGEST_PROVEEDOR_TRASLADO"
export const ERROR_AUTOSUGGEST_ESPECIALIDAD_MEDICA = "ERROR_AUTOSUGGEST_ESPECIALIDAD_MEDICA"

//LOADING AUTOSUGGEST
export const LOADING_AUTOSUGGEST_BUSQUEDA_EMPLEADOR = "LOADING_AUTOSUGGEST_BUSQUEDA_EMPLEADOR"
export const LOADING_AUTOSUGGEST_BUSQUEDA_EMPLEADOR_TODOS = "LOADING_AUTOSUGGEST_BUSQUEDA_EMPLEADOR_TODOS"
export const LOADING_AUTOSUGGEST_AGENTE_CAUSANTE = "LOADING_AUTOSUGGEST_AGENTE_CAUSANTE"
export const LOADING_AUTOSUGGEST_AGENTE_MATERIAL = "LOADING_AUTOSUGGEST_AGENTE_MATERIAL"
export const LOADING_AUTOSUGGEST_DIAGNOSTICO_CIE10 = "LOADING_AUTOSUGGEST_DIAGNOSTICO_CIE10"
export const LOADING_AUTOSUGGEST_DIAGNOSTICO_CIE10_2 = "LOADING_AUTOSUGGEST_DIAGNOSTICO_CIE10_2"
export const LOADING_AUTOSUGGEST_DIAGNOSTICO_CIE10_3 = "LOADING_AUTOSUGGEST_DIAGNOSTICO_CIE10_3"
export const LOADING_AUTOSUGGEST_FORMA_ACCIDENTE = "LOADING_AUTOSUGGEST_FORMA_ACCIDENTE"
export const LOADING_AUTOSUGGEST_NATURALEZA_SINIESTRO = "LOADING_AUTOSUGGEST_NATURALEZA_SINIESTRO"
export const LOADING_AUTOSUGGEST_NATURALEZA_SINIESTRO_2 = "LOADING_AUTOSUGGEST_NATURALEZA_SINIESTRO_2"
export const LOADING_AUTOSUGGEST_NATURALEZA_SINIESTRO_3 = "LOADING_AUTOSUGGEST_NATURALEZA_SINIESTRO_3"
export const LOADING_AUTOSUGGEST_ZONA_AFECCION = "LOADING_AUTOSUGGEST_ZONA_AFECCION"
export const LOADING_AUTOSUGGEST_ZONA_AFECCION_2 = "LOADING_AUTOSUGGEST_ZONA_AFECCION_2"
export const LOADING_AUTOSUGGEST_ZONA_AFECCION_3 = "LOADING_AUTOSUGGEST_ZONA_AFECCION_3"
export const LOADING_AUTOSUGGEST_PROVINCIA = "LOADING_AUTOSUGGEST_PROVINCIA"
export const LOADING_AUTOSUGGEST_LOCALIDADES = "LOADING_AUTOSUGGEST_LOCALIDADES"
export const LOADING_AUTOSUGGEST_CENTROS_MEDICOS = "LOADING_AUTOSUGGEST_CENTROS_MEDICOS"
export const LOADING_AUTOSUGGEST_CALLE = "LOADING_AUTOSUGGEST_CALLE"
export const LOADING_AUTOSUGGEST_CODIGO_POSTAL = "LOADING_AUTOSUGGEST_CODIGO_POSTAL"
export const LOADING_AUTOSUGGEST_OCUPACION = "LOADING_AUTOSUGGEST_OCUPACION"
export const LOADING_AUTOSUGGEST_TAREA = "LOADING_AUTOSUGGEST_TAREA"
export const LOADING_AUTOSUGGEST_SEDE = "LOADING_AUTOSUGGEST_SEDE"
export const LOADING_AUTOSUGGEST_TIPO_SEDE = "LOADING_AUTOSUGGEST_TIPO_SEDE"
export const LOADING_AUTOSUGGEST_PROVEEDOR_TRASLADO = "LOADING_AUTOSUGGEST_PROVEEDOR_TRASLADO"
export const LOADING_SINIESTROS_MULTIPLES_TABLE = "LOADING_SINIESTROS_MULTIPLES_TABLE"
export const LOADING_SINIESTROS_MULTIPLES_SAVE = "LOADING_SINIESTROS_MULTIPLES_SAVE"
export const CAMPANA_NOTIFICACIONES = "CAMPANA_NOTIFICACIONES"
export const LOADING_AUTOSUGGEST_ESPECIALIDAD_MEDICA = "LOADING_AUTOSUGGEST_ESPECIALIDAD_MEDICA"
export const LOADING_DATA_TIPOS_VALOR_VIAJE_NEGATIVO = "LOADING_DATA_TIPOS_VALOR_VIAJE_NEGATIVO"
export const LOADING_LISTADO_DESTINOS_FRECUENTES = "LOADING_LISTADO_DESTINOS_FRECUENTES"

//IMPORTAR EXPORTAR
export const SET_LOCALIDADES_IMPORTADAS = "SET_LOCALIDADES_IMPORTADAS"
export const SET_LOADING_IMPORTAR = "SET_PN_IMPORTADAS"
export const SET_LOADING_IMMPRIMIR_PDF_AUTORIZACION = "SET_LOADING_IMMPRIMIR_PDF_AUTORIZACION"
export const SET_LOADING_DESCARGAR_PDF_ORDEN_MEDICA = "SET_LOADING_DESCARGAR_PDF_ORDEN_MEDICA"
export const SET_LOADING_DESCARGAR_PDF_INICIO_SG = "SET_LOADING_DESCARGAR_PDF_INICIO_SG"
export const SET_LOADING_DESCARGAR_PDF_TRASLADO = "SET_LOADING_DESCARGAR_PDF_TRASLADO"

//PRESTACIONES
export const SET_LISTADO_PRESTACIONES_NOMENCLADAS = "SET_LISTADO_PRESTACIONES_NOMENCLADAS"
export const SET_LISTADO_PRESTACIONES_NO_NOMENCLADAS = "SET_LISTADO_PRESTACIONES_NO_NOMENCLADAS"
export const SET_LOADING_LISTAR_PRESTACIONES = "SET_LOADING_LISTAR_PRESTACIONES"
export const SET_ERROR_LISTAR_PRESTACIONES = "SET_ERROR_LISTAR_PRESTACIONES"
export const SET_LOADING_ADD_EDIT_PRESTACIONES_NO_NOMENCLADAS = "SET_LOADING_ADD_EDIT_PRESTACIONES_NO_NOMENCLADAS"
export const LOADING_BUSQUEDA_PRESTACIONES = "LOADING_BUSQUEDA_PRESTACIONES"
export const SET_DATA_PRESTACIONES = "SET_DATA_PRESTACIONES"

//MODULO CONVENIO
export const GET_MODULO = "GET_MODULO"
export const SET_LOADING_MODULO = "SET_LOADING_MODULO"
export const SET_ERROR_MODULO = "SET_LOADING_ERROR"
export const GET_INCLUSIONES_MODULO = "GET_INCLUSIONES_MODULO"
export const SET_LOADING_INCLUSIONES_MODULO = "SET_LOADING_INCLUSIONES_MODULO"
export const GET_INCLUSIONES_REPETIDAS = "GET_INCLUSIONES_REPETIDAS"
export const SET_LOADING_INCLUSIONES_REPETIDAS = "SET_LOADING_INCLUSIONES_REPETIDAS"
export const SET_LOADING_SAVE_INCLUSIONES = "SET_LOADING_SAVE_INCLUSIONES"
export const SET_LISTADO_TIPO_PRESTACION = "SET_LISTADO_TIPO_PRESTACION"
export const SET_LOADING_SAVE_EDIT_MODULO = "SET_LOADING_SAVE_EDIT_MODULO"
export const SET_CONVENIOS_INCLUIDOS = "SET_CONVENIOS_INCLUIDOS"
export const SET_LOADING_CONVENIOS_INCLUIDOS = "SET_LOADING_CONVENIOS_INCLUIDOS"
export const GET_LISTADO_MODULOS = "GET_LISTADO_MODULOS"
export const SET_LOADING_LISTADO_MODULOS = "SET_LOADING_LISTADO_MODULOS"
export const SET_LOADING_IMPACTAR_CONVENIOS = "SET_LOADING_IMPACTAR_CONVENIOS"

//CONVENIO
export const SET_REQUEST_CONVENIO = "SET_REQUEST_CONVENIO"
export const SET_CONVENIO_ACTUAL = "SET_CONVENIO_ACTUAL"
export const SET_LOADING_CONVENIO_ACTUAL = "SET_LOADING_CONVENIO_ACTUAL"
export const SET_ERROR_CONVENIO_ACTUAL = "SET_ERROR_CONVENIO_ACTUAL"
export const SET_PN = "SET_PN"
export const SET_PNN = "SET_PNN"
export const SET_PNBU = "SET_PNBU"
export const SET_MODULOS = "SET_MODULOS"
export const SET_LOADING_PN = "SET_LOADING_PN"
export const SET_LOADING_PNN = "SET_LOADING_PNN"
export const SET_LOADING_PNBU = "SET_LOADING_PNBU"
export const SET_LOADING_MODULOS = "SET_LOADING_MODULOS"
export const SET_ERROR_PN = "SET_ERROR_PN"
export const SET_ERROR_PNN = "SET_ERROR_PNN"
export const SET_ERROR_PNBU = "SET_ERROR_PNBU"
export const SET_ERROR_MODULOS = "SET_ERROR_MODULOS"
export const SET_PRESTACIONES_PREQUIRUGICAS = "SET_PRESTACIONES_PREQUIRURGICAS"
export const SET_LOADING_PRESTACIONES_PREQUIRURGICAS = "SET_LOADING_PRESTACIONES_PREQUIRURGICAS"
export const SET_CONVENIO_HISTORICO = "SET_CONVENIO_HISTORICO"
export const SET_LOADING_CONVENIO_HISTORICO = "SET_LOADING_CONVENIO_HISTORICO"
export const SET_ERROR_CONVENIO_HISTORICO = "SET_ERROR_CONVENIO_HISTORICO"
export const SET_CONVENIO_FUTURO = "SET_CONVENIO_FUTURO"
export const SET_LOADING_CONVENIO_FUTURO = "SET_LOADING_CONVENIO_FUTURO"
export const SET_ERROR_CONVENIO_FUTURO = "SET_ERROR_CONVENIO_FUTURO"
export const SET_PROVEEDORES_CONVENIO = "SET_PROVEEDORES_CON_CONVENIO"
export const SET_LOADING_PROVEEDORES_CONVENIO = "SET_LOADING_PROVEEDORES_CON_CONVENIO"
export const SET_ERROR_PROVEEDORES_CONVENIO = "SET_ERROR_PROVEEDORES_CON_CONVENIO"
export const SET_PRESTACIONES_PROVEEDOR = "SET_PRESTACIONES_PROVEEDOR"
export const SET_LOADING_PRESTACIONES_PROVEEDOR = "SET_LOADING_PRESTACIONES_PROVEEDOR"
export const SET_ERROR_PRESTACIONES_PROVEEDOR = "SET_ERROR_PRESTACIONES_PROVEEDOR"

//AUDITORIA MEDICA
export const SET_SNACKBAR_AUDITORIA = "SET_SNACKBAR_AUDITORIA"
export const SET_REQUEST_FILTROS = "SET_REQUEST_FILTROS"
export const CLEAR_REQUEST_FILTROS = "CLEAR_REQUEST_FILTROS"
export const GET_CANTIDAD_NOTIFICACIONES_AM = "GET_CANTIDAD_NOTIFICACIONES_AM"
export const SET_DATA_TABLERO_AM = "SET_DATA_TABLERO_AM"
export const SET_LOADING_TABLERO_AM = "SET_LOADING_TABLERO_AM"
export const SET_DATA_INDICADORES_SINIESTROS = "SET_DATA_INDICADORES_SINIESTROS"
export const SET_LOADING_INDICADORES_SINIESTROS = "SET_LOADING_INDICADORES_SINIESTROS"
export const SET_DATA_AUTORIZACIONES_PEDIENTES = "SET_DATA_AUTORIZACIONES_PEDIENTES"
export const SET_LOADING_AUTORIZACIONES_PEDIENTES = "SET_LOADING_AUTORIZACIONES_PEDIENTES"
export const SET_DATA_NUEVOS_INGRESOS = "SET_DATA_NUEVOS_INGRESOS"
export const SET_LOADING_NUEVOS_INGRESOS = "SET_LOADING_NUEVOS_INGRESOS"
export const SET_DATA_SINIESTROS_ACTIVOS = "SET_DATA_SINIESTROS_ACTIVOS"
export const SET_LOADING_SINIESTROS_ACTIVOS = "SET_LOADING_SINIESTROS_ACTIVOS"
export const SET_DATA_SINIESTROS_ILT_VENCIDOS = "SET_DATA_SINIESTROS_ILT_VENCIDOS"
export const SET_LOADING_SINIESTROS_ILT_VENCIDOS = "SET_LOADING_SINIESTROS_ILT_VENCIDOS"
export const SET_DATA_PRACTICAS_PENDIENTES_AUTORIZACION = "SET_DATA_PRACTICAS_PENDIENTES_AUTORIZACION"
export const SET_LOADING_PRACTICAS_PENDIENTES_AUTORIZACION = "SET_LOADING_PRACTICAS_PENDIENTES_AUTORIZACION"
export const SET_DATA_DETALLE_AUTORIZACION_PENDIENTE = "SET_DATA_DETALLE_AUTORIZACION_PENDIENTE"
export const SET_LOADING_DETALLE_AUTORIZACION_PENDIENTE = "SET_LOADING_DETALLE_AUTORIZACION_PENDIENTE"
export const SET_DATA_MAT_QX_AUTORIZACION_PENDIENTE = "SET_DATA_MAT_QX_AUTORIZACION_PENDIENTE"
export const SET_LOADING_MAT_QX_AUTORIZACION_PENDIENTE = "SET_LOADING_MAT_QX_AUTORIZACION_PENDIENTE"
export const SET_DATA_PEDIDO_MATERIALES_QX = "SET_DATA_PEDIDO_MATERIALES_QX"
export const SET_LOADING_PEDIDO_MATERIALES_QX = "SET_LOADING_PEDIDO_MATERIALES_QX"
export const SET_DATA_MATERIALES_XQ_PEDIDO = "SET_DATA_MATERIALES_XQ_PEDIDO"
export const SET_LOADING_MATERIALES_XQ_PEDIDO = "MATERIALES_XQ_PEDIDO"
export const SET_LOADING_SAVE_NUEVO_PROXIMO_CONTACTO = "SET_LOADING_SAVE_NUEVO_PROXIMO_CONTACTO"

//LOGINTOOLS
export const SET_PARAMETROS = "SET_PARAMETROS"
export const SET_LOADING_PARAMETROS = "SET_LOADING_PARAMETROS"
export const SET_LOADING_SAVE_PARAMETROS = "SET_LOADING_SAVE_PARAMETROS"

//TURNOS
export const SET_DATA_HISTORIAL_POR_DENUNCIA = "SET_DATA_HISTORIAL_SINIESTROS"
export const SET_LOADING_HISTORIAL_POR_DENUNCIA = "SET_LOADING_HISTORIAL_SINIESTROS"
export const SET_DATA_HISTORIAL_POR_TURNO = "SET_DATA_INFO_TURNOS"
export const SET_LOADING_HISTORIAL_POR_TURNO = "SET_LOADING_INFO_TURNOS"

//CIRUGIAS
export const SET_LOADING_DATOS_CIRUGIAS_POR_DENUNCIA = "SET_LOADING_DATOS_CIRUGIAS_POR_DENUNCIA"
export const SET_DATOS_CIRUGIAS_POR_DENUNCIA = "SET_DATOS_CIRUGIAS_POR_DENUNCIA"
export const SET_DATOS_OBSERVACIONES_POR_CIRUGIA = "SET_DATOS_OBSERVACIONES_POR_CIRUGIA"
export const SET_LOADING_OBSERVACIONES_CIRUGIA = "SET_LOADING_OBSERVACIONES_CIRUGIA"